name: 'Weekly Umami Report'

on:
  schedule:
    # Run weekly at 7 AM UTC on Mondays
    - cron: '0 7 * * 1'

jobs:
  daily-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run report script
        run: node app.js
        env:
          UMAMI_URL: ${{secrets.UMAMI_URL}}
          UMAMI_ID_WEBSITE_ID: ${{secrets.UMAMI_ID_WEBSITE_ID}}
          UMAMI_USERNAME: ${{secrets.UMAMI_USERNAME}}
          UMAMI_PASSWORD: ${{secrets.UMAMI_PASSWORD}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
